# generated by datamodel-codegen:
#   filename:  agent.schema.json
#   timestamp: 2026-04-06T13:58:57+00:00

from __future__ import annotations

from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, constr


class Agent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID = Field(..., description='Unique agent identifier')
    name: constr(min_length=1, max_length=255) = Field(
        ..., description='Agent display name'
    )
    owner_id: UUID = Field(..., description='User who owns this agent')
    token_hash: constr(min_length=64, max_length=64) | None = Field(
        None, description='SHA256 hash of agent token (amc_*)'
    )
    is_active: bool = Field(..., description='Whether agent can make API calls')
    scopes: list[constr(pattern=r'^[a-z]+:(read|write|execute)$')] | None = Field(
        None, description='Permitted operations (memories:write, trading:execute)'
    )
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None
