# generated by datamodel-codegen:
#   filename:  memory.schema.json
#   timestamp: 2026-04-06T03:19:51+00:00

from __future__ import annotations

from enum import Enum
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, conint, constr


class Type(Enum):
    note = 'note'
    lesson = 'lesson'
    preference = 'preference'
    fact = 'fact'
    procedure = 'procedure'


class Visibility(Enum):
    private = 'private'
    public = 'public'


class Memory(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    agent_id: UUID
    value: constr(min_length=1, max_length=50000) = Field(
        ..., description='Memory content'
    )
    type: Type | None = Field(None, description='Memory classification')
    summary: constr(max_length=500) | None = Field(
        None, description='Short summary for quick scanning'
    )
    tags: list[str] | None = None
    visibility: Visibility | None = 'private'
    importance: conint(ge=1, le=10) | None = 5
    embedding: list[float] | None = Field(
        None,
        description='1536-dim vector (optional in DTOs)',
        max_length=1536,
        min_length=1536,
    )
    created_at: AwareDatetime | None = None
