# generated by datamodel-codegen:
#   filename:  trade.schema.json
#   timestamp: 2026-04-06T12:38:32+00:00

from __future__ import annotations

from enum import Enum
from typing import Any
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, constr


class Side(Enum):
    long = 'long'
    short = 'short'


class Status(Enum):
    open = 'open'
    closed = 'closed'
    cancelled = 'cancelled'


class Trade(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: int = Field(..., description='Trade ID (SERIAL in Postgres)')
    agent_name: str = Field(..., description='Display name of agent that created trade')
    agent_id: UUID | None = Field(None, description='Agent UUID (internal reference)')
    symbol: constr(min_length=1, max_length=64) = Field(
        ..., description='Trading symbol (AAPL, BTC, etc.)'
    )
    side: Side
    entry_price: constr(pattern=r'^[0-9]+(\.[0-9]+)?$') = Field(
        ..., description='Stored as TEXT in DB for precision'
    )
    entry_quantity: int = Field(..., description='Number of shares/contracts')
    status: Status | None = 'open'
    entry_time: AwareDatetime
    exit_time: AwareDatetime | None = None
    exit_price: constr(pattern=r'^[0-9]+(\.[0-9]+)?$') | None = Field(
        None, description='Exit price (TEXT for precision)'
    )
    pnl: float | None = Field(None, description='Profit/loss in dollars')
    pnl_percent: float | None = Field(None, description='Profit/loss as percentage')
    strategy: constr(max_length=255) | None = Field(
        None, description='Strategy that generated this trade'
    )
    paper: bool | None = Field(True, description='Paper trading vs real money')
    decision_memory_id: UUID | None = Field(
        None, description='Memory explaining why trade was taken'
    )
    outcome_memory_id: UUID | None = Field(
        None, description='Memory analyzing trade result'
    )
    metadata: dict[str, Any] | None = Field(
        None, description='Additional strategy-specific data'
    )
